### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by vbarba** [meezaan/linode-k8s-autoscaler#5]
When running the container I get the following error:

```[2021-07-16T17:35:00.517004+01:00] AUTOSCALER.INFO: Created Logger... [] []
[2021-07-16T17:35:00.518586+01:00] AUTOSCALER.INFO: Building Kubernetes Config... [] []
[16-Jul-2021 17:35:00 Europe/London] PHP Deprecated:  Required parameter $callback follows optional parameter $params in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/Client.php on line 170
[2021-07-16T17:35:00.531412+01:00] AUTOSCALER.INFO: Creating Kubernetes Client [] []
[2021-07-16T17:35:00.532062+01:00] AUTOSCALER.INFO: Create Linode API Client... [] []
[2021-07-16T17:35:00.541912+01:00] AUTOSCALER.INFO: Start Monitoring Cluster... [] []
[2021-07-16T17:35:00.542051+01:00] AUTOSCALER.INFO: Autoscale Trigger is set to: cpu [] []
[2021-07-16T17:35:00.542080+01:00] AUTOSCALER.INFO: Autoscale Trigger Type is set to: requested [] []
[2021-07-16T17:35:00.542102+01:00] AUTOSCALER.INFO: Create Counter... [] []
[2021-07-16T17:35:00.542373+01:00] AUTOSCALER.INFO: Get Nodes' and Metrics details... [] []
[16-Jul-2021 17:35:01 Europe/London] PHP Warning:  Trying to access array offset on value of type null in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 118
[16-Jul-2021 17:35:01 Europe/London] PHP Warning:  foreach() argument must be of type array|object, null given in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 118
[16-Jul-2021 17:35:01 Europe/London] PHP Warning:  Trying to access array offset on value of type null in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 122
[16-Jul-2021 17:35:01 Europe/London] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php:122
Stack trace:
#0 /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php(122): array_key_exists('continue', NULL)
#1 /autoscaler/src/Kubernetes/Nodes.php(88): KubernetesClient\ResourceList->stream()
#2 /autoscaler/src/Kubernetes/Nodes.php(41): AutoScaler\Kubernetes\Nodes->calculateUsedResources()
#3 /autoscaler/bin/autoscale(58): AutoScaler\Kubernetes\Nodes->__construct(Object(KubernetesClient\Client))
#4 {main}
  thrown in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 122
```

I checked and the config file is in place and the LINODE token should be valid.

Do you think what I may doing wrong here?

Regards

**Comment by meezaan** [comment]
It is possible that you have pods with resources allocated to them.

**Comment by vbarba** [comment]
Thank you for your answer!

Yes. I am using the lastest tag. also tried with the previous with same result.

I have pods without resources allocated. It is a node pool with only 1 pod running per node as it is a daemonset.

**Comment by meezaan** [comment]
You need at least one pod / deployment with resources allocated, otherwise the cluster has no way of knowing when to scale. You are also running on request mode, which is fine (the plan is to deprecate the limit mode because there is never enough time to scale when the limit is breached so it creates a false sense of security).

You will just need to set the request part of the resources, you should not need the limit.

**Comment by vbarba** [comment]
Oh, ok. I see.

I thought that it uses the metrics and node level. 

What if I'm running only one pod on each node? should I set the pod resources to match node resources? Then the cluster will be with 100% resources allocated always.

Is it possible to scale base on usage and not allocation?

Regards!

**Comment by meezaan** [comment]
Yes, and it is documented in the README file. I am away for the next few days so I suggest you have an attempt at using the docs to do it. Otherwise I can help out when I'm back next week.

**Comment by vbarba** [comment]
Thank you very much. I see now. If I use the TRIGGER = 'used' must I allocate resources to the pod?

**Comment by meezaan** [comment]
If I recall from memory, no, because it takes actual usage / available resources on nodes.

**Comment by vbarba** [comment]
Unfortunately, same thing:

```% ./k8s/linode-autoscaler/local.sh
[2021-07-19T17:45:54.231164+01:00] AUTOSCALER.INFO: Created Logger... [] []
[2021-07-19T17:45:54.232425+01:00] AUTOSCALER.INFO: Building Kubernetes Config... [] []
[2021-07-19T17:45:54.253622+01:00] AUTOSCALER.INFO: Creating Kubernetes Client [] []
[19-Jul-2021 17:45:54 Europe/London] PHP Deprecated:  Required parameter $callback follows optional parameter $params in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/Client.php on line 170
[2021-07-19T17:45:54.255909+01:00] AUTOSCALER.INFO: Create Linode API Client... [] []
[2021-07-19T17:45:54.267958+01:00] AUTOSCALER.INFO: Start Monitoring Cluster... [] []
[2021-07-19T17:45:54.268044+01:00] AUTOSCALER.INFO: Autoscale Trigger is set to: cpu [] []
[2021-07-19T17:45:54.268070+01:00] AUTOSCALER.INFO: Autoscale Trigger Type is set to: used [] []
[2021-07-19T17:45:54.268084+01:00] AUTOSCALER.INFO: Create Counter... [] []
[2021-07-19T17:45:54.268350+01:00] AUTOSCALER.INFO: Get Nodes' and Metrics details... [] []
[19-Jul-2021 17:45:55 Europe/London] PHP Warning:  Trying to access array offset on value of type null in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 118
[19-Jul-2021 17:45:55 Europe/London] PHP Warning:  foreach() argument must be of type array|object, null given in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 118
[19-Jul-2021 17:45:55 Europe/London] PHP Warning:  Trying to access array offset on value of type null in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 122
[19-Jul-2021 17:45:55 Europe/London] PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php:122
Stack trace:
#0 /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php(122): array_key_exists('continue', NULL)
#1 /autoscaler/src/Kubernetes/Nodes.php(88): KubernetesClient\ResourceList->stream()
#2 /autoscaler/src/Kubernetes/Nodes.php(41): AutoScaler\Kubernetes\Nodes->calculateUsedResources()
#3 /autoscaler/bin/autoscale(58): AutoScaler\Kubernetes\Nodes->__construct(Object(KubernetesClient\Client))
#4 {main}
  thrown in /autoscaler/vendor/travisghansen/kubernetes-client-php/src/KubernetesClient/ResourceList.php on line 122```

**Comment by vbarba** [comment]
Ok. Forget everything. I just deployed the metrics-server and it is working now! 

Thank you very much for your help and creating this!
